services:

  app:
    image: app/frontend:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
        NODE_OPTIONS: "--openssl-legacy-provider"
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
    command: ["npm", "start"]
