version: "3.8"

services:
  api:
    build: ../src
    volumes:
      - ../src:/var/www
    entrypoint: ["/bin/bash", "/var/www/run_dev.sh"]
    depends_on:
      - database
      - rabbit
    ports:
    - "8000:8000"

  test:
    build: ../src
    volumes:
      - ../src:/var/www
    entrypoint: [ "/bin/bash", "/var/www/run_test.sh" ]

  database:
    image: postgres:13.2
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: app
      POSTGRES_DB: app

  rabbit:
    image: rabbitmq:3.8.12-alpine
    ports:
    - "5672:5672"
    - "15672:15672"